apiVersion: apps/v1
kind: Deployment
metadata:
  name: cidemo
  namespace: cidemo-v2-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cidemo
  template:
    metadata:
      labels:
        app: cidemo
    spec:
      containers:
      - name: cidemo
        image: docker.io/cgi-kubiya/cidemo:latest
        resources:
          requests:
            cpu: 10m
            memory: 768Mi

