apiVersion: apps/v1
kind: Deployment
metadata:
  name: cidemo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cidemo
  template:
    metadata:
      labels:
        app: cidemo
    spec:
      containers:
      - name: cidemo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: 80

