app:
  name: cidemo
  namespace: cidemo-dev
  resources:
    requests:
      cpu: 10m
      memory: 768Mi
  replicas: 3
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

